import type { editor } from 'monaco-editor'
import type { ThemeName } from '@/components/theme-provider'

type MonacoThemeData = editor.IStandaloneThemeData

const loneDuskBro: MonacoThemeData = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: '', foreground: 'abb2bf' },
    { token: 'comment', foreground: '5c6370', fontStyle: 'italic' },
    { token: 'keyword', foreground: 'c678dd' },
    { token: 'keyword.control', foreground: 'c678dd' },
    { token: 'storage.type', foreground: 'c678dd' },
    { token: 'type', foreground: 'e5c07b' },
    { token: 'type.identifier', foreground: 'e5c07b' },
    { token: 'string', foreground: '98c379' },
    { token: 'number', foreground: 'd19a66' },
    { token: 'constant', foreground: 'd19a66' },
    { token: 'variable', foreground: 'e06c75' },
    { token: 'identifier', foreground: 'abb2bf' },
    { token: 'delimiter', foreground: 'abb2bf' },
    { token: 'annotation', foreground: 'e5c07b' },
  ],
  colors: {
    'editor.background': '#282c34',
    'editor.foreground': '#abb2bf',
    'editor.lineHighlightBackground': '#2c313a',
    'editor.selectionBackground': '#3e4451',
    'editor.inactiveSelectionBackground': '#3a3f4b',
    'editorCursor.foreground': '#528bff',
    'editorWhitespace.foreground': '#3e4451',
    'editorIndentGuide.background': '#3e4451',
    'editorIndentGuide.activeBackground': '#5c6370',
    'editorLineNumber.foreground': '#5c6370',
    'editorLineNumber.activeForeground': '#abb2bf',
    'editorGutter.background': '#282c34',
    'editorWidget.background': '#21252b',
    'editorWidget.border': '#3e4451',
    'input.background': '#1d1f23',
    'input.border': '#3e4451',
    'scrollbar.shadow': '#00000000',
    'scrollbarSlider.background': '#3e445180',
    'scrollbarSlider.hoverBackground': '#3e4451b3',
    'scrollbarSlider.activeBackground': '#3e4451',
  },
}

const groovebox: MonacoThemeData = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: '', foreground: 'ebdbb2' },
    { token: 'comment', foreground: '928374', fontStyle: 'italic' },
    { token: 'keyword', foreground: 'fb4934' },
    { token: 'keyword.control', foreground: 'fb4934' },
    { token: 'storage.type', foreground: 'fb4934' },
    { token: 'type', foreground: 'fabd2f' },
    { token: 'type.identifier', foreground: 'fabd2f' },
    { token: 'string', foreground: 'b8bb26' },
    { token: 'number', foreground: 'd3869b' },
    { token: 'constant', foreground: 'd3869b' },
    { token: 'variable', foreground: '83a598' },
    { token: 'identifier', foreground: 'ebdbb2' },
    { token: 'delimiter', foreground: 'ebdbb2' },
    { token: 'annotation', foreground: 'fabd2f' },
  ],
  colors: {
    'editor.background': '#282828',
    'editor.foreground': '#ebdbb2',
    'editor.lineHighlightBackground': '#32302f',
    'editor.selectionBackground': '#504945',
    'editor.inactiveSelectionBackground': '#3c3836',
    'editorCursor.foreground': '#fabd2f',
    'editorWhitespace.foreground': '#504945',
    'editorIndentGuide.background': '#504945',
    'editorIndentGuide.activeBackground': '#928374',
    'editorLineNumber.foreground': '#665c54',
    'editorLineNumber.activeForeground': '#ebdbb2',
    'editorGutter.background': '#282828',
    'editorWidget.background': '#1d2021',
    'editorWidget.border': '#504945',
    'input.background': '#1d2021',
    'input.border': '#504945',
    'scrollbar.shadow': '#00000000',
    'scrollbarSlider.background': '#50494580',
    'scrollbarSlider.hoverBackground': '#504945b3',
    'scrollbarSlider.activeBackground': '#504945',
  },
}

const legitIde: MonacoThemeData = {
  base: 'vs',
  inherit: true,
  rules: [
    { token: '', foreground: '000000' },
    { token: 'comment', foreground: '8c8c8c', fontStyle: 'italic' },
    { token: 'keyword', foreground: '0033b3' },
    { token: 'keyword.control', foreground: '0033b3' },
    { token: 'storage.type', foreground: '0033b3' },
    { token: 'type', foreground: '000000', fontStyle: 'bold' },
    { token: 'type.identifier', foreground: '000000' },
    { token: 'string', foreground: '067d17' },
    { token: 'number', foreground: '1750eb' },
    { token: 'constant', foreground: '871094' },
    { token: 'variable', foreground: '000000' },
    { token: 'identifier', foreground: '000000' },
    { token: 'delimiter', foreground: '000000' },
    { token: 'annotation', foreground: '9e880d' },
  ],
  colors: {
    'editor.background': '#ffffff',
    'editor.foreground': '#000000',
    'editor.lineHighlightBackground': '#f5f5f5',
    'editor.selectionBackground': '#a6d2ff',
    'editor.inactiveSelectionBackground': '#d4d4d4',
    'editorCursor.foreground': '#000000',
    'editorWhitespace.foreground': '#d1d1d1',
    'editorIndentGuide.background': '#d1d1d1',
    'editorIndentGuide.activeBackground': '#939393',
    'editorLineNumber.foreground': '#999999',
    'editorLineNumber.activeForeground': '#000000',
    'editorGutter.background': '#f3f3f3',
    'editorWidget.background': '#f5f5f5',
    'editorWidget.border': '#d1d1d1',
    'input.background': '#ffffff',
    'input.border': '#d1d1d1',
    'scrollbar.shadow': '#00000010',
    'scrollbarSlider.background': '#d1d1d180',
    'scrollbarSlider.hoverBackground': '#d1d1d1b3',
    'scrollbarSlider.activeBackground': '#d1d1d1',
  },
}

const adMajorem: MonacoThemeData = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: '', foreground: 'C4B5A0' },
    { token: 'comment', foreground: '3D2A1A', fontStyle: 'italic' },
    { token: 'keyword', foreground: '8B0000' },
    { token: 'keyword.control', foreground: '8B0000' },
    { token: 'storage.type', foreground: '8B0000' },
    { token: 'type', foreground: '8899AA' },
    { token: 'type.identifier', foreground: '8899AA' },
    { token: 'string', foreground: '6B2020' },
    { token: 'number', foreground: '705030' },
    { token: 'constant', foreground: '705030' },
    { token: 'variable', foreground: 'C4B5A0' },
    { token: 'identifier', foreground: 'C4B5A0' },
    { token: 'delimiter', foreground: '6B5A4A' },
    { token: 'annotation', foreground: '3D0000' },
  ],
  colors: {
    'editor.background': '#0D0808',
    'editor.foreground': '#C4B5A0',
    'editor.lineHighlightBackground': '#160E0A',
    'editor.selectionBackground': '#3D000040',
    'editor.inactiveSelectionBackground': '#1E1410',
    'editorCursor.foreground': '#8B0000',
    'editorWhitespace.foreground': '#1E1410',
    'editorIndentGuide.background': '#1E1410',
    'editorIndentGuide.activeBackground': '#30201A',
    'editorLineNumber.foreground': '#30201A',
    'editorLineNumber.activeForeground': '#6B5A4A',
    'editorGutter.background': '#0D0808',
    'editorWidget.background': '#0A0605',
    'editorWidget.border': '#30201A',
    'input.background': '#0A0605',
    'input.border': '#30201A',
    'scrollbar.shadow': '#00000000',
    'scrollbarSlider.background': '#30201A40',
    'scrollbarSlider.hoverBackground': '#5C000050',
    'scrollbarSlider.activeBackground': '#30201A',
  },
}

export const MONACO_THEMES: Partial<Record<ThemeName, { name: string; data: MonacoThemeData }>> = {
  'lone-dusk-bro': { name: 'lone-dusk-bro', data: loneDuskBro },
  groovebox: { name: 'groovebox', data: groovebox },
  'legit-ide': { name: 'legit-ide', data: legitIde },
  'ad-majorem': { name: 'ad-majorem', data: adMajorem },
}
